### ISSUE TITLE
Getting an error when trying to connect (First attempt at this)

### ISSUE THREAD

**Issue by Phate1989** [KelvinTegelaar/AutotaskAPI#14]
I set the credential and add the autotaskapiauth and that goes through.

Retrieving webservices URI based on username
Setting AutotaskBaseURI to https://webservices15.autotask.net/ATServicesRest/ using version V1.0
Setting API resource parameters. This may take a moment.

When I try and run 
Get-AutotaskAPIResource -resource Companies -SimpleSearch "isactive eq $true"

I get the following.

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Program Files\WindowsPowerShell\Modules\AutoTaskAPI\0.9.9\AutoTaskAPI.psm1:234 char:52
+             $ErrResp = $streamReader.ReadToEnd() | ConvertFrom-Json
+                                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by Phate1989** [comment]
![image](https://user-images.githubusercontent.com/7754628/85190750-7451c100-b289-11ea-90fc-53a88a3592ab.png)

**Comment by KelvinTegelaar** [comment]
Hi!

The https://webservices15.autotask.net/ server has not yet been updated to 2020.2. This means the REST API isn't available yet. add-Autotaskapiauth works because authentication is done in a central autotask zone, and not on your server specifically. 

The good news is that on the 30th of june you should be updated, and you'll be able to use the module after that.

Would you like me to keep the bug report open until after release, so we can follow-up?

**Comment by Phate1989** [comment]
Sure, thanks for that info.  I will try again on the 30th.

**Comment by KelvinTegelaar** [comment]
I believe webservices15 is now upgraded. Can you try again? :)

**Comment by Phate1989** [comment]
Working Great thanks Kelvin excellent work, hope to contribute!

**Comment by Phate1989** [comment]
Thanks!
