### ISSUE TITLE
easier method to create body, including picklist

### ISSUE THREAD

**Issue by KelvinTegelaar** [KelvinTegelaar/AutotaskAPI#6]
We should improve new-autotask body, to automatically set the values for that specific body, this would also allow the usage of labels for the picklist values.

**Comment by KelvinTegelaar** [comment]
example; New-autotaskbody -resource "companies" -name "CompanyName" -Status SuperDuperStatus would create the following Pscustomobject:

@{
AccountName = "CompanyName"
AccountStatus = 15
}

**Comment by KelvinTegelaar** [comment]
found that it's quite simple to grab all resources and included picklists in 2 minutes and 20 seconds:
Minutes           : 2
Seconds           : 20
Milliseconds      : 151

issue with this is that it feels like too long, and i'd rather have it dynamic.

Looking into above example by using dynamic parameters once more. just feels overkillish.

**Comment by joncz** [comment]
How do you feel about keeping a cache of the picklist items in the module and only grab the relevant items if they're referenced and the cache variable is null?

**Comment by klemmestad** [comment]
I have a bit of experience with this from the powershell module for the SOAP API. I would say caching is the way to go. Dynamic parameters get my vote. It allows for intellisense support for picklist values. The way I chose to solve it way back when was to create a wrapper function per resource type to get the right parameters with the correct validation settings. At the time I ended up using static parameters, but I generated the code dynamically. I would really like to revisit this solution using dynamic parameters. 
Using wrapper functions could fit in, because at the end of the day, all my wrapper functions called the same core function - with much the same syntax as yours 😊

**Comment by KelvinTegelaar** [comment]
My guess then would be that it's best to rewrite the New-Autotaskbody to support dynamic parameters. The reason I'd like to only change that function is to keep the rest of the module as fast loading as we could.

This has the added benefit for anyone not using New-Autotaskbody that the module loads in seconds, and for anyone that does it's picked up and cached. 

The workflow I have in my head would be;

**First run:**
- New-Autotaskbody is called.
- Dynamic Params script downloads **_all_** available information for each resource via /entityinformation/fields and /entitityinformation/userdefinedfields to disk. 
-Dynamic parameters are created based on downloaded fields, including picklist value options.

On later runs, the download is skipped if the files are found. To refresh the cache we add the switch -Refreshcache.

I'll try playing around with this idea in the beta channel this weekend.

**Comment by klemmestad** [comment]
There are some issues with this:
1. Picklists change over time. You will need a system to detect changes in picklists and update your cache when needed.
2. Picklists differ between Autotask tenants. You will need to keep track of which Autotask tenant your cache files are for.
3. You cannot cache to disk on Azure Automation, which is a popular use case.

I would suggest using dynamic parameters in which you determine which resource is in use and get field info for this resource only. Store in a variable (probably in a hashtable) with a timestamp. If variable exists and timestamp is new enough, use variable next time, otherwise hit the API again for updated field info.

**Comment by KelvinTegelaar** [comment]
Haven't been able to give this the love it deserves yet. Hopefully coming weekend :)
